// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzep9rmIZfmV5yf-RuvW35VVCUYqLZNss',
    appId: '1:1060412485273:web:cd4eed20b5b4350606d208',
    messagingSenderId: '1060412485273',
    projectId: 'temp-project-cb639',
    authDomain: 'temp-project-cb639.firebaseapp.com',
    storageBucket: 'temp-project-cb639.appspot.com',
    measurementId: 'G-YHFGB3FECB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyBPRyNEFfCO4hDwZ-QBcQKUitKVwDGyE',
    appId: '1:1060412485273:android:3897eb44a278ea5206d208',
    messagingSenderId: '1060412485273',
    projectId: 'temp-project-cb639',
    storageBucket: 'temp-project-cb639.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekHIOMU8uQu3OpkqkWYv1VqEm1s8cdDo',
    appId: '1:1060412485273:ios:a0915453ff24240e06d208',
    messagingSenderId: '1060412485273',
    projectId: 'temp-project-cb639',
    storageBucket: 'temp-project-cb639.appspot.com',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCekHIOMU8uQu3OpkqkWYv1VqEm1s8cdDo',
    appId: '1:1060412485273:ios:1a89d445e9ca6df206d208',
    messagingSenderId: '1060412485273',
    projectId: 'temp-project-cb639',
    storageBucket: 'temp-project-cb639.appspot.com',
    iosBundleId: 'com.example.notificationApp.RunnerTests',
  );
}
